### ISSUE TITLE
Signature matching algorithm does not computer properly  [BUG]

### ISSUE THREAD

**Issue by jeffward01** [ravenyue/ImageMatchNet#1]
Hello! @yu-jingfeng 

Great work on this library!

I saw that your library is based off of:  https://github.com/ProvenanceLabs/image-match ([Documentation here](https://image-match.readthedocs.io/en/latest/docs.html))

In your example, when comparing Image #1 & Image #2 (Which are the same as the python example), yours returns `0.4600757541644907` 

The Python example returns: `Returns 0.22095170140933634. ` 

In the [documentation of the Python example](https://image-match.readthedocs.io/en/latest/signatures.html) it says: 
> Normalized distances of less than 0.40 are very likely matches. 

Is this a bug? Can you explain what is going on here please? Is the development complete for a .NET port of this Python library?

Thanks!

**Comment by ravenyue** [comment]
Thank you, @jeffward01

Because the `AutoEntropyCrop` option (default `true`) uses the `image.Mutate(o => o.EntropyCrop())` method to crop 2.jpg but not 1.jpg, so there was a difference in the result.

Now the auto crop has been removed and the image is not cropped by default, please set the `SignatureOptions.CropPercentiles` option if you need to crop
